name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: npm install

      - name: Deploy
        run: |
          git config --global user.name 'Albina Salkayeva'
          git config --global user.email 'salkaeva.a@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          npm run deploy
